race condition
YuraBondarenko/Multithreading-1 pull request #1
Opened 2021-02-19 21:07 UTC by YuraBondarenko

2021-02-22 11:46 UTC, vlykhvar approved these changes

2021-02-22 15:37 UTC, RomanDubovskyi requested changes

2021-02-22 15:37 UTC, RomanDubovskyi commented on src/main/java/Counter.java
> +    public void counter(String threadName) {
```suggestion
    public void count(String threadName) {
```
method names are usually verbs

2021-02-22 15:37 UTC, RomanDubovskyi commented on src/main/java/Counter.java
> +        for (; counter < MAX; counter++) {
for such situation while loop suits better

2021-02-23 08:28 UTC, RomanDubovskyi approved these changes

2021-02-23 16:56 UTC, merged